### ISSUE TITLE
Katalog instalacji

### ISSUE THREAD

**Issue by adthinzad** [CryptoDevTV/SolBo#11]
Czy bot mógłby zapisywać wsio do katalogu instalacji. Teraz bez względu na inne miejsce - tworzy i tak katalog na C://solbo , i tam zapisuje logi. 
W razie padaki systemu - wszystko od nowa.
Dzięki.

**Comment by tkowalczyk** [comment]
cenna uwaga, zobaczę czy pakiet, którego używam do logowania pozwala na szybką zamianę ścieżki w sposób programowy :)

**Comment by edeco100** [comment]
Co do folderu zapisu danych w pliku konfiguracyjnym solbo.json, to na razie warto zaznaczyć, ze musi on zostać niezmieniony.
Ja zmieniłem na własny i po uruchomieniu miałem błąd. O taki:
"2020/05/20 21:11:52.901|FATAL|SOLBO| 'U' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $.Strategy.Available[0].StoragePath | LineNumber: 12 | BytePositionInLine: 27."
Bot uruchomił się po ponownym ustawieniu ścieżki na oryginalną.

**Comment by tkowalczyk** [comment]
> Co do folderu zapisu danych w pliku konfiguracyjnym solbo.json, to na razie warto zaznaczyć, ze musi on zostać niezmieniony.
> Ja zmieniłem na własny i po uruchomieniu miałem błąd. O taki:
> "2020/05/20 21:11:52.901|FATAL|SOLBO| 'U' is an invalid escapable character within a JSON string. The string should be correctly escaped. Path: $.Strategy.Available[0].StoragePath | LineNumber: 12 | BytePositionInLine: 27."
> Bot uruchomił się po ponownym ustawieniu ścieżki na oryginalną.

ścieżkę można jak najbardziej zmienić, należy ją tylko podać zgodnie z standardem Windows tj.
`C:\\Tomek\\sciezka\\`

podwójny znak `\\`

chyba, że uruchamiamy bota na systemach UNIXowych to wtedy ścieżka powinna być zgodna z konwencją systemu. Sugerowałbym również nie używać znaków diaktrycznych (żźćół) i innych z pozostałych języków.

**Comment by tkowalczyk** [comment]
Postanowiłem usunąć parametr `storagepath` bo jak się okazało wprowadzał trochę zamieszania, dodatkowo mógł powodować pewne komplikacje pomiędzy systemami operacyjnymi. Teraz plik z logiem jak plik z kursem będzie trafiał do katalogu z którego uruchamiany jest bot. Nie trzeba nic definiować i podawać żadnych ścieżek, wystarczy pobrać bota, rozpakować go tam gdzie ma się znajdować i uruchomić :) hope it helps
