### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by adthinzad** [CryptoDevTV/SolBo#15]
Tomek, jeśli za bardzo przesadzam - to mnie pohamuj! :)

Czy jest szansa na jakie GUI z przyciskami WIO i PRR... (czyt. start/stop).
Może się zdarzyć sytuacja, że kryptosie polecą o więcej procentów niż zapisane, i chcielibyśmy poczekać, aż się sytuacja uspokoi (haltując tylko bota a nie wyłączając go), i dokupić w manualu możliwie jak najniżej?..

**Comment by tkowalczyk** [comment]
Poruszyłeś tutaj bardzo złożony temat, krótka odpowiedź brzmi - nie, ze względu na koszty jakie niesie utrzymanie takiego środowiska i w zasadzie całkowita zmiana paradygmatu w jakim działa bot.

To co obecnie można zrobić by przybliżyć trochę wizję o której piszesz to:
- zrobić prosty GUI (w formie aplikacji webowej, dostępnej przez przeglądarkę), który pozwala na generowanie pliku konfiguracyjnego (`solbo.json) i pobranie na własny komputer / VPS.
- dodać w pliku konfiguracyjnym przełącznik (w formie oczywiście parametru konfiguracyjnego), którego odpowiednie ustawienie będzie powodować przejścia w bota w stan bezczynności (tzn. 1- bot aktywny - kupuje, sprzedaje, śledzi ceny; 0 - bot nieaktywny, cały czas uruchomiony ale czekający na przełączenie go w stan 1).

Co myślisz o takiej propozycji?

**Comment by adthinzad** [comment]
O to to! Przełącznik będzie całkiem ok! Powiedzenie, że jestem totalnym nobem programowania, byłoby obelgą dla nobów... 
Zdawałem sobie sprawę z czasu i trudności wykonania "obudowy wizualnej" - nie kosztów. ;)

**Comment by tkowalczyk** [comment]
@adthinzad takie rozwiązanie będzie generować koszty utrzymania interfejsu Web (do sterowania botem i jeszcze kilka innych kwestii), a też nie zamierzam robić z tego aplikacji desktopowej bo boty w takiej formie słabo się sprawdzają.

Zamykam ten issue i w jego miejsce tworzę dwa nowe.

https://github.com/CryptoDevTV/SolBo/issues/18
https://github.com/CryptoDevTV/SolBo/issues/17
