### ISSUE TITLE
zmiana ceny

### ISSUE THREAD

**Issue by dominikbtc** [CryptoDevTV/SolBo#22]
zmiana ceny do kupna i sprzedaży mniejsza niż 1

**Comment by tkowalczyk** [comment]
mniejsza niż 1%?

**Comment by dominikbtc** [comment]
tak  głównie chodzi mi o kupno , jeżeli ma być w przryszlości take profit limit :)). 1 procent spadek przy naszych średnich oczywiście to musi być już niezły dump. Moja strategia będzie polegała na małych wahaniach i częstych łapania ceny , dlatego 1 procent to już dużo oczywiście przy łapaniu ceny ze średnich>

**Comment by dominikbtc** [comment]
Czy jak będzie take profit limit to bot nie realizująć sprzedaży będzie szukał kolejnej okazji zakupowej ? Czy to już oddzielny temat?

**Comment by edeco100** [comment]
> tak głównie chodzi mi o kupno , jeżeli ma być w przryszlości take profit limit :)). 1 procent spadek przy naszych średnich oczywiście to musi być już niezły dump. Moja strategia będzie polegała na małych wahaniach i częstych łapania ceny , dlatego 1 procent to już dużo oczywiście przy łapaniu ceny ze średnich>

widzę Dominik, że kombinujesz dokładnie tak samo jak ja. Skalpowanie ci się marzy ;)
Sorry za OT.
A co do meritum. To bardzo dobry pomysł. Lepiej 1000x złapać 100sat niż czekać w nieskończoność na złapanie 50K

**Comment by tkowalczyk** [comment]
> 
> 
> Czy jak będzie take profit limit to bot nie realizująć sprzedaży będzie szukał kolejnej okazji zakupowej ? Czy to już oddzielny temat?

to oddzielny temat

**Comment by tkowalczyk** [comment]
> 
> 
> tak głównie chodzi mi o kupno , jeżeli ma być w przryszlości take profit limit :)). 1 procent spadek przy naszych średnich oczywiście to musi być już niezły dump. Moja strategia będzie polegała na małych wahaniach i częstych łapania ceny , dlatego 1 procent to już dużo oczywiście przy łapaniu ceny ze średnich>

zgadzam się Panowie, zrobię tak by procenty w konfiguracji nie były liczbami całkowitymi :)

**Comment by dominikbtc** [comment]
super CryptoDev
