### ISSUE TITLE
BOT kupił drożej jak sprzedał?

### ISSUE THREAD

**Issue by edeco100** [CryptoDevTV/SolBo#25]
Pobrałem, zgodnie z info na YT odpaliłem kilka par, w osobnych folderach... uruchomiło się i zbierało informacje. Tak więc możliwe jest przeszukiwanie rożnych par jednocześnie. Na razie w osobnych folderach. Być może to wystarczy. Być może w bliżej nieokreślonej perspektywie czasowej da się to zmienić. Myślę, ze to będzie zależało od testów jakie robimy.

Na jednej wygenerowało zakup... i tutaj zauważyłem, że chyba bot będzie do przebudowy.
Ale najpierw to co zostało pobrane.

dla testów zakup i sprzedaż ustawiłem 0,15% (w zalezności od pary są to wystarczające marginesy do wygenerowania skromnego profitu) aby mieć pewność, że w końcu uda się złapać zakup i sprzedaż. Oczywiście sam biorę odpowiedzialność za ustawienia.
#1
TEST MODE START
2020/05/30 14:52:13.743|INFO|SOLBO| STOPLOSS => Price (0,01565000) increased from the average (0,0156) by 0,32%
2020/05/30 14:52:13.838|INFO|SOLBO| STOPLOSS => Price reached (False), bought before (0)
2020/05/30 14:52:13.872|INFO|SOLBO| SELL => Price (0,01565000) increased from the average (0,0156) by 0,32%
2020/05/30 14:52:14.201|INFO|SOLBO| SELL => Price reached (True), bought before (0)
2020/05/30 14:52:14.225|INFO|SOLBO| BUY => Price (0,01565000) increased from the average (0,0156) by 0,32%
2020/05/30 14:52:14.225|INFO|SOLBO| BUY => Price reached (False), bought before (0)
2020/05/30 14:52:14.237|INFO|SOLBO|
TEST MODE END
Jak rozumiem średnia wyliczona to 0,0156

#3
TEST MODE START
2020/05/30 14:53:58.909|INFO|SOLBO| STOPLOSS => Price (0,01567000) has fallen from the average (0,0157) by 0,19%
2020/05/30 14:53:58.959|INFO|SOLBO| STOPLOSS => Price reached (False), bought before (0)
2020/05/30 14:53:58.959|INFO|SOLBO| SELL => Price (0,01567000) has fallen from the average (0,0157) by 0,19%
2020/05/30 14:53:58.978|INFO|SOLBO| SELL => Price reached (False), bought before (0)
2020/05/30 14:53:58.978|INFO|SOLBO| BUY => Price (0,01567000) has fallen from the average (0,0157) by 0,19%
2020/05/30 14:53:59.014|INFO|SOLBO| BUY => Price reached (True), bought before (1)
2020/05/30 14:53:59.050|INFO|SOLBO|
TEST MODE END
Tutaj  średnia to 0,0157 a więc wzrosła. I tutaj widzę, ze został dokonany zakup po cenie 0,01567 czyli wyższej jak średnia z kroku 1. Przynajmniej tak rozumiem dane w logach.

#23
 TEST MODE START
2020/05/30 15:05:58.887|INFO|SOLBO| STOPLOSS => Price (0,01564000) increased from the average (0,0156) by 0,26%
2020/05/30 15:05:58.902|INFO|SOLBO| STOPLOSS => Price reached (False), bought before (1)
2020/05/30 15:05:58.902|INFO|SOLBO| SELL => Price (0,01564000) increased from the average (0,0156) by 0,26%
2020/05/30 15:05:58.902|INFO|SOLBO| SELL => Price reached (True), bought before (0)
2020/05/30 15:05:58.902|INFO|SOLBO| BUY => Price (0,01564000) increased from the average (0,0156) by 0,26%
2020/05/30 15:05:58.919|INFO|SOLBO| BUY => Price reached (False), bought before (0)
2020/05/30 15:05:58.919|INFO|SOLBO|
TEST MODE END

Jak dobrze rozumiem działanie to tutaj wygenerowała się sprzedaż po cenie 0,01564
Czyli sprzedaż po cenie niższej.

Chciałbym aby odnieśli się inni testujący bota.

Wydaje mi się, ze powinno to wyglądać troszkę inaczej. Tylko co z trendem na rynku?

1. A więc po zapuszczeniu bota liczy średnią i zapamiętuje ją.
2. wylicza cenę do zakupu na podstawie podanych %-ów
3. pojawia się nowa cena. kupiło T/N
4. jeżeli N to liczy kolejną średnią, jeżeli jest wyższa to zostawiamy starą, jeżeli niższe to zapamiętujemy ją i liczymy cenę zakupu.
5. i tak w kółko aż zostanie wygenerowany zakup.
6. w tym kroku na podstawie ceny zakupu wyliczamy cenę sprzedaży na podstawie zadanych %-ów
(A jest liczona średnia i jak jest wyższa to generuje się sprzedaż i sprzedaje nawet gdy cena zakupu była wyższa.)

Tak to wygląda z mojej strony. Mogę się mylić i chciałbym aby ktoś wykazał moje błędne rozumowanie.

**Comment by dominikbtc** [comment]
Witam edeco100 to samo pisałem w komentarzach, że duże prawdopodobieństwo jest, że bot sprzeda ze stratą, a szczególnie przy skalpowaniu jakie chcemy robić. Przy kupnie to średnie to  jest GENIALNY pomysł tak genialny bo jak będzie nagły spadek o 10% to nie kupi nam 200 razy ale już przy sprzedaży to zły pomysł musi byc staly zysk i szukanie kolejnej okazji zakupowej bez realizacji sprzedaży poprzedniego zakupu . Nie wiem jak Ty ale ja wierze w naszego CryptoDeva że coś wymyśli, może róbmy mu kanapki , bawmy się z dziećmi a niech on siedzi i programuje? pozdrawiam

**Comment by tkowalczyk** [comment]
@edeco100 @dominikbtc odniosę się oczywiście do treści tego Issue dajcie mi trochę czasu na przeanalizowanie tego :)

**może róbmy mu kanapki , bawmy się z dziećmi** <-- w sedno, tutaj masz u mnie dużego LIKEa 👍

**Comment by tkowalczyk** [comment]
@edeco100 @dominikbtc w tym tygodniu opublikuje nową wersję bota z możliwością grania na giełdzie, wtedy ponownie zrobimy testy i zweryfikujemy wszystko żeby mieć pewność czy prawidłowo działa. Parę błędów również wychwyciłem i poprawiłem.

**Comment by tkowalczyk** [comment]
otwieram ponownie, problem nadal występuje ale już mam pomysł i wiem jak go rozwiązać definitywnie :)
