### ISSUE TITLE
Attempted to divide by zero

### ISSUE THREAD

**Issue by slashdotkom** [CryptoDevTV/SolBo#26]
Zauważyłem że na parze np ADABTC bot nie potrafi wyciągnąć średniej i dalej nie wykonuje poleceń z kodu źródłowego tylko spamuje Attempted to divide by zero. Cena jest pobierana prawidłowo.
![Solbo](https://user-images.githubusercontent.com/67323758/85405072-29bd9680-b560-11ea-8b47-8ddd6e551540.png)

Czy to błąd z mojej strony ? Dziękuję za pomoc :)

**Comment by tkowalczyk** [comment]
OK muszę to zweryfikować, a możesz jeszcze wrzucić tutaj swój plik konfiguracyjny? `solbo.json` ?

**Comment by slashdotkom** [comment]
Jasne :)
![Solbo](https://user-images.githubusercontent.com/67323758/85460518-9a39d700-b5a3-11ea-8490-b91b22e2aff4.jpg)

**Comment by tkowalczyk** [comment]
@slashdotkom był to błąd w implementacji, którego już nie będzie w nowej wersji oznaczonej https://github.com/CryptoDevTV/SolBo/milestone/3, bardzo dziękuje za zgłoszenie tego gdyż mogło się to objawiać również na innych parach :)
