### ISSUE TITLE
Błąd podczas uruchomienia w tle

### ISSUE THREAD

**Issue by VaXeS13** [CryptoDevTV/SolBo#44]
dotnet run &
![image](https://user-images.githubusercontent.com/18619276/91352106-a59ac000-e7e9-11ea-893b-4aac1f831858.png)

**Comment by urbaniakmichal** [comment]
tylko jedna osoba napisała ze ma problem, dodatkowo informacji i błędzie jest mało, dodatkowo nie widać zeby ta osoba była zainteresowana co się dzieje z tym issue poniewaz nie wykazuje zadnej aktywnosci w tym temacie  - wg mnie spokojnie ten issue mozna zamknąć.
