### ISSUE TITLE
Ograniczenie/optymalizacja zużycia ramu 

### ISSUE THREAD

**Issue by dlg94** [CryptoDevTV/SolBo#51]
Po kilku dniach działania bota bot potrafi zajmować nawet około 900 mb ramu.

**Comment by dlg94** [comment]
![Zrzut ekranu 2020-09-21 104819](https://user-images.githubusercontent.com/68918361/93749163-b9bfba80-fbf9-11ea-9958-bef8e4105851.png)

**Comment by tkowalczyk** [comment]
Prawdopodobnie rozwiązałem to w wersji `0.4.0`, która czeka na Release. Póki co zamykam.
