### ISSUE TITLE
Solbo Kucoin

### ISSUE THREAD

**Issue by PiotrSobiecki** [CryptoDevTV/SolBo#52]
NIezależnie jaką walutę wybierzemy zawsze kwota bazowa jest o wartości 66,07 
![Przechwytywanie](https://user-images.githubusercontent.com/55161384/94033976-c727a100-fdc1-11ea-8138-af0ba283fbca.JPG)

**Comment by PiotrSobiecki** [comment]
ok kwota która pokazuje dotyczy innego krypto , jak przelałem wszystko na main accout poza waluta ustawioną do trajdu , to jest okej

**Comment by tkowalczyk** [comment]
@PiotrSobiecki czy tutaj jest jeszcze jakiś problem? coś wymaga wyjaśnienia?

**Comment by PiotrSobiecki** [comment]
no tu problem tej ilosci pozostaje , jak mam kilka krypto na trading accout to pokazuje złe ilosći ,zaczytuje ilosć z innej krypto .
