### ISSUE TITLE
Order siez increment invalid

### ISSUE THREAD

**Issue by PiotrSobiecki** [CryptoDevTV/SolBo#53]
bot sie uruchamia i kupuje
ale przy próbie sprzedaży znów jest bład Order size Increament invalid

**Comment by PiotrSobiecki** [comment]
Przy zmianie pary wyrzuca bład zakupu FUNDS increament INVALID

**Comment by tkowalczyk** [comment]
@PiotrSobiecki czy mogę już zamknąć to issue?

**Comment by PiotrSobiecki** [comment]
TAK :)

pon., 19 paź 2020 o 13:30 Tomasz Kowalczyk <notifications@github.com>
napisał(a):
