### ISSUE TITLE
Wysycenie ramu na 4GB

### ISSUE THREAD

**Issue by adcool** [CryptoDevTV/SolBo#61]
Zauważyłem, że bot bardzo wysyca ram, po restarcie apki, zapisuje log do starszego pliczku, po czym rozpoczyna pisać do nowego, (2x bot, co 3min, średnio 3GB ram starcza na dzień :) ) po restarcie apki, ram wraca

![image](https://user-images.githubusercontent.com/62216228/109433213-820e3780-7a0f-11eb-9bf7-4ae52d76aafb.png)

**Comment by tkowalczyk** [comment]
Prawdopodobnie rozwiązałem to w wersji `0.4.0`, która czeka na Release. Póki co zamykam.
