### ISSUE TITLE
Uruchamianie bota w tle linux VPS

### ISSUE THREAD

**Issue by jarmatys** [CryptoDevTV/SolBo#62]
Cześć,

w jaki sposób uruchomić bota w tle poleceniem  "dotnet run"?

Próbowałem użyć nohup niestety, w tym przypadku bot nie ma uprawnień do zapisywania w plikach i rzuca błędami :(

Komenda, której próbowałem użyć: sudo nohup `sudo dotnet run` &>/dev/null &

**Comment by tkowalczyk** [comment]
`nohup dotnet GemTracker.Agent.dll > /dev/null 2>&1 &`
